window.SIM_DATA = {
  scopePresets: [
    { name: { ko: "1 kHz 사인 기준 신호", en: "1 kHz Sine Reference" }, waveform: "sine", amplitude: 2.4, frequency: 1000, offset: 0, noise: 2 },
    { name: { ko: "Square Logic Clock", en: "Square Logic Clock" }, waveform: "square", amplitude: 2.5, frequency: 500, offset: 0, noise: 1 },
    { name: { ko: "AM 라디오 엔벌로프", en: "AM Radio Envelope" }, waveform: "am", amplitude: 3.2, frequency: 1200, offset: 0.6, noise: 4 },
    { name: { ko: "모터 리플", en: "Motor Ripple" }, waveform: "sawtooth", amplitude: 1.5, frequency: 220, offset: 1.2, noise: 9 },
    { name: { ko: "센서 Chirp", en: "Sensor Chirp" }, waveform: "chirp", amplitude: 2.0, frequency: 250, offset: -0.2, noise: 6 },
  ],
  waveformOptions: [
    { value: "sine", label: { ko: "사인파", en: "Sine" } },
    { value: "square", label: { ko: "구형파", en: "Square" } },
    { value: "triangle", label: { ko: "삼각파", en: "Triangle" } },
    { value: "sawtooth", label: { ko: "톱니파", en: "Sawtooth" } },
    { value: "am", label: { ko: "AM", en: "AM" } },
    { value: "chirp", label: { ko: "Chirp", en: "Chirp" } },
  ],
  antennaCatalog: [
    { id: "biconical", label: { ko: "바이코니컬 안테나 [20 MHz ~ 200 MHz]", en: "Biconical Antenna [20 MHz ~ 200 MHz]" }, minMHz: 20, maxMHz: 200, gainDb: 1.8 },
    { id: "logPeriodic", label: { ko: "로그주기 안테나 [200 MHz ~ 1000 MHz]", en: "Log-Periodic Antenna [200 MHz ~ 1000 MHz]" }, minMHz: 200, maxMHz: 1000, gainDb: 6.4 },
    { id: "combo", label: { ko: "콤보 브로드밴드 안테나 [30 MHz ~ 1000 MHz]", en: "Broadband Combo Antenna [30 MHz ~ 1000 MHz]" }, minMHz: 30, maxMHz: 1000, gainDb: 4.5 },
    { id: "horn", label: { ko: "혼 안테나 [1000 MHz ~ 18000 MHz]", en: "Horn Antenna [1000 MHz ~ 18000 MHz]" }, minMHz: 1000, maxMHz: 18000, gainDb: 10 },
  ],
  sourceProfiles: [
    { id: "cw", label: { ko: "CW 단일 톤", en: "CW Single Tone" } },
    { id: "am", label: { ko: "AM 캐리어", en: "AM Carrier" } },
    { id: "clock", label: { ko: "클록 고조파", en: "Clock Harmonics" } },
  ],
  shieldMaterials: [
    { id: "steel", label: { ko: "강판 차폐함", en: "Steel Shield Box" }, baseDb: 12 },
    { id: "aluminum", label: { ko: "알루미늄 차폐함", en: "Aluminum Shield Box" }, baseDb: 9 },
    { id: "copperMesh", label: { ko: "구리 메시 차폐함", en: "Copper Mesh Shield Box" }, baseDb: 7 },
  ],
  englishStaticText: {
    brandEyebrow: "Test / Instrument Practice",
    brandTitle: "EMC Test Simulator",
    navHome: "Home",
    navShield: "Shielding Test",
    navPci: "PCI Test",
    navToolsLabel: "Support Instruments",
    navScope: "Oscilloscope",
    navAnalyzer: "Signal Analyzer",
    navGenerator: "Signal Generator",
    navManual: "Manual",
    homeTitle: "Test Simulator Home",
    homeDescription: "The instrument screens remain available as supporting tools, but the main home flow is now organized around test simulators. Start with shielding first, then extend toward PCI in the next MVP.",
    homeScopeCta: "Start Shielding Test",
    homeAnalyzerCta: "PCI Coming Soon",
    homeManualCta: "Open Manual",
    homeFeatureEyebrow: "MVP Focus",
    homeFeatureTitle: "Primary Flow",
    homeFeature1: "1. Capture the baseline in open LOS",
    homeFeature2: "2. Place the receive antenna into the shield box and compare",
    homeFeature3: "3. Use the instrument screens from the top nav as supporting tools",
    statusAvailable: "Available",
    statusPlanned: "Planned",
    homeCardScopeTitle: "Shielding Test",
    homeCardScopeDesc: "Place LOS transmit and receive antennas, save the baseline, then compare attenuation before and after applying the virtual shield box.",
    homeCardScopeButton: "Open Test",
    homeCardAnalyzerTitle: "PCI Test",
    homeCardAnalyzerDesc: "PCI is reserved for the next MVP. The home entry is visible now, while the working simulation remains focused on shielding.",
    homeCardAnalyzerButton: "Coming Soon",
    homeCardGeneratorTitle: "Signal Generator",
    homeCardGeneratorDesc: "This will be added next as a separate transmitter source linked to the analyzer environment.",
    homeCardGeneratorButton: "Coming Soon",
    scopeEyebrow: "Support Instrument",
    scopeTitle: "Oscilloscope",
    scopeDescription: "Choose a sample signal and practice stabilizing the waveform with scale and trigger settings.",
    sampleEyebrow: "Sample",
    sampleTitle: "Measured Signal",
    presetLabel: "Preset",
    waveformLabel: "Waveform",
    amplitudeLabel: "Amplitude (V)",
    frequencyLabel: "Frequency (Hz)",
    offsetLabel: "Offset (V)",
    noiseLabel: "Noise (%)",
    channelEyebrow: "Channel",
    channelTitle: "CH1 Vertical",
    couplingLabel: "Coupling",
    invertLabel: "Invert",
    toolbarTriggerLabel: "Trigger Level",
    measureEyebrow: "Auto Measure",
    measureTitle: "Readout",
    metricFreq: "Freq",
    metricPeriod: "Period",
    metricMean: "Mean",
    metricMax: "Max",
    hintsEyebrow: "Practice",
    hintsTitle: "Suggested Tasks",
    hint1: "Switch to AC coupling and compare how the mean value changes.",
    hint2: "Change Time / div until the trigger locks the waveform steadily.",
    hint3: "Increase noise and compare how Vpp and Vrms respond.",
    analyzerEyebrow: "Test Simulator",
    analyzerTitle: "Shielding Test",
    analyzerDescription: "Drag antenna cards onto the LOS board, then compare the baseline and shielded receive spectrum.",
    shieldAntennaEyebrow: "Shielding Test STEP 1 / 4",
    shieldAntennaTitle: "Antenna Setup",
    shieldAntennaDescription: "Place the transmit antenna, receive antenna, and shield-box slot first to build the LOS environment.",
    shieldAntennaNextButton: "Next: Enter Test Values",
    shieldSetupEyebrow: "Shielding Test STEP 2 / 4",
    shieldSetupTitle: "Enter Test Values",
    shieldSetupDescription: "Set LOS distance, shielding conditions, and analyzer sweep values before moving to the generator step.",
    shieldSetupBackButton: "Back: Antenna Setup",
    shieldSetupNextButton: "Next: Generator",
    flowSummaryEyebrow: "Experiment Summary",
    flowSummaryTitle: "Entered Values",
    flowSummaryTx: "Tx Antenna",
    flowSummaryRx: "Rx Antenna",
    flowSummaryPlacement: "Receive Position",
    flowSummaryDistance: "LOS Distance",
    flowSummaryShieldMaterial: "Shield Material",
    flowSummaryShieldEffectiveness: "Shielding",
    flowSummaryShieldLeakage: "Leakage",
    flowSummaryGeneratorFreq: "Generator Frequency",
    flowSummaryGeneratorLevel: "Generator Level",
    flowSummaryGeneratorState: "Transmit State",
    flowSummaryCenter: "Center",
    flowSummarySpan: "Span",
    flowSummaryRbw: "RBW",
    supportToolsEyebrow: "Support Instruments",
    supportToolsTitle: "Quick Tool Access",
    supportToolsNote: "Open the auxiliary instrument screens at any point in the experiment to review the same entered values and measurements.",
    workflowStepAntenna: "1. Antenna Setup",
    workflowAntennaTitle: "Place Antennas",
    workflowAntennaDesc: "Start by placing antennas into the TX, RX, and shield-box slots.",
    workflowStepGenerator: "2. Generator Setup",
    workflowGeneratorTitle: "Signal Generator",
    workflowGeneratorDesc: "Set frequency and LEVEL, then return to check the analyzer.",
    workflowToGeneratorButton: "Go Set Generator",
    workflowStepAnalyzer: "3. Analyzer Check",
    workflowAnalyzerTitle: "Reference / Spectrum Check",
    workflowAnalyzerDesc: "Finally, store the reference and compare the spectra before and after shielding.",
    workflowSettingsEyebrow: "Settings",
    workflowSettingsTitle: "Current Test Values",
    workflowTxValueLabel: "Tx Antenna",
    workflowRxValueLabel: "Rx Antenna",
    workflowRxPlacementLabel: "Receive Position",
    workflowGeneratorFreqLabel: "Generator Frequency",
    workflowGeneratorLevelLabel: "Generator Level",
    workflowCenterLabel: "Analyzer Center",
    workflowRbwLabel: "RBW",
    quickSetupEyebrow: "Direct Input",
    quickSetupTitle: "2. Enter Test Values",
    quickSetupNote: "After placing the antennas, enter the LOS distance, shielding values, and analyzer sweep values here, then move to the generator step.",
    quickDistanceLabel: "LOS Distance",
    quickShieldEffectivenessLabel: "Shielding",
    quickShieldLeakageLabel: "Leakage",
    quickCenterLabel: "Analyzer Center",
    quickSpanLabel: "Span",
    quickRbwLabel: "RBW",
    quickSetupToGeneratorButton: "3. Go To Generator",
    antennaDeckEyebrow: "Antenna Deck",
    antennaDeckTitle: "Drag Antenna Cards",
    antennaDeckNote: "The image area is intentionally left blank for later artwork. Drag any of the four antenna cards into the transmit or receive slot.",
    stageEyebrow: "Test Stage",
    stageTitle: "LOS Placement Board",
    stageLead: "The top row holds the transmit and receive slots, and the bottom slot is the shield box. Dropping a card syncs the detailed settings and analyzer automatically.",
    stageTxSlot: "Transmit Antenna Slot",
    stageRxSlot: "Receive Antenna Slot",
    stageShieldSlot: "Shield Box Slot",
    stageImagePlaceholder: "Image Placeholder",
    stageLosLabel: "LOS Path",
    stageDropHint: "Tip: place the receive antenna into the shield box slot when you want the shielded condition.",
    captureBaselineButton: "Store Reference",
    clearBaselineButton: "Clear Reference",
    analyzerSourceEyebrow: "Link Setup",
    analyzerSourceTitle: "LOS Antennas",
    txAntennaLabel: "Transmit Antenna",
    rxAntennaLabel: "Receive Antenna",
    sourceProfileLabel: "Source Profile",
    carrierLabel: "Transmit Frequency",
    txPowerLabel: "Transmit Power (dBm)",
    openGeneratorButton: "Open Signal Generator",
    distanceLabel: "LOS Distance (m)",
    shieldEyebrow: "Shielding",
    shieldTitle: "Receive Antenna Shield Box",
    shieldEnabledLabel: "Use Shield Box",
    shieldMaterialLabel: "Shield Material",
    shieldEffectivenessLabel: "Base Shielding (dB)",
    shieldLeakageLabel: "Gap / Aperture Leakage (%)",
    shieldNote: "In most workflows, store the reference first in the open LOS state with the shield box disabled.",
    analyzerSweepEyebrow: "Sweep Setup",
    analyzerSweepTitle: "Signal Analyzer",
    autoTuneButton: "Tune to Tx Frequency",
    referenceStateLabel: "Reference",
    analyzerResultEyebrow: "Results",
    analyzerResultTitle: "Key Measurements",
    peakFreqLabel: "Peak Frequency",
    peakLevelLabel: "Peak Level",
    deltaLabel: "Delta vs Ref",
    shieldLossLabel: "Shield Loss",
    pathLossLabel: "Path Loss",
    noiseFloorLabel: "Noise Floor",
    analyzerEnvEyebrow: "Environment",
    analyzerEnvTitle: "Antenna Recognition",
    summaryTxAntenna: "Tx Antenna",
    summaryRxAntenna: "Rx Antenna",
    summaryOverlap: "Overlap Band",
    summaryCarrierBand: "Carrier Status",
    summaryShieldState: "Shield State",
    summaryReference: "Reference",
    analyzerPracticeEyebrow: "Practice",
    analyzerPracticeTitle: "Suggested Tasks",
    analyzerHint1: "Select the biconical antenna and store a reference first in the open LOS condition.",
    analyzerHint2: "Place the receive antenna into the shield box and compare delta while changing material and leakage.",
    analyzerHint3: "Move the transmit frequency outside the overlap band and observe how antenna recognition changes.",
    generatorEyebrow: "Support Instrument",
    generatorTitle: "Signal Generator",
    generatorDescription: "Set the transmit frequency and level like a signal generator and feed the shielding experiment directly.",
    generatorFreqEyebrow: "Frequency",
    generatorFreqTitle: "Frequency",
    generatorValueLabel: "Value",
    generatorFreqNote: "Entered values are kept in standby. The analyzer updates only when you press Fire.",
    generatorLevelEyebrow: "Level",
    generatorLevelTitle: "Level",
    generatorLevelInputLabel: "Output Level (dBm)",
    generatorLevelNote: "Set the dBm level, then press Fire to transmit with that level.",
    generatorFireButton: "Fire!",
    generatorStopButton: "Stop",
    generatorUnitMeta: "Unit",
    generatorLinkMeta: "Experiment Link",
    generatorSummaryEyebrow: "Link State",
    generatorSummaryTitle: "Transmit Summary",
    generatorSummaryFreq: "Generator Frequency",
    generatorSummaryLevel: "Generator Level",
    generatorSummaryOutput: "RF Output",
    generatorSummaryAnalyzer: "Analyzer Feed",
    generatorHintEyebrow: "Tips",
    generatorHintTitle: "Suggested Flow",
    generatorHint1: "Enter a Frequency value and switch units until the target transmit frequency is correct.",
    generatorHint2: "Press LEVEL, then adjust the dBm value and compare the receive level change.",
    generatorHint3: "The analyzer peak appears only after Fire. Press Stop to return near the noise floor.",
    generatorToAntennaButton: "Back To Step 2",
    generatorToAnalyzerButton: "Check Analyzer",
    manualEyebrow: "Manual",
    manualTitle: "EMC Test Simulator User Guide",
    manualLead: "Use this guide to learn the shielding workflow first, then use the instrument screens as supporting tools before touching real hardware.",
    manualStartTitle: "1. Quick Start",
    manualStart1: "From the home screen, enter the shielding test first, then use the oscilloscope and signal analyzer from the top navigation as supporting tools when needed.",
    manualStart2: "On the oscilloscope, change the sample and waveform conditions and practice reading the waveform.",
    manualStart3: "On the signal analyzer, define the LOS antennas and transmit settings, then store a reference.",
    manualStart4: "Next, place the receive antenna inside the virtual shield box and compare attenuation against the reference.",
    manualScopeTitle: "2. Oscilloscope",
    manualScope1: "Use the left panel to change the sample, waveform, amplitude, frequency, offset, and noise.",
    manualScope2: "Use Time/div and trigger controls in the center screen to stabilize the waveform.",
    manualScope3: "Read Vpp, Vrms, frequency, and mean values on the right panel.",
    manualAnalyzerTitle: "3. Signal Analyzer",
    manualAnalyzer1: "When you select the transmit and receive antennas, each antenna range is recognized automatically.",
    manualAnalyzer2: "For example, the biconical antenna is shown as a 20 MHz to 200 MHz antenna.",
    manualAnalyzer3: "If the transmit frequency is inside the overlap band, the spectral peak remains strong. Outside the band, attenuation and warnings appear.",
    manualAnalyzer4: "Once a reference is stored, the analyzer overlays the current trace with the saved reference trace.",
    manualShieldTitle: "4. Shielding Simulation",
    manualShield1: "Change the shield material, base shielding value, and leakage percentage to see the attenuation shift.",
    manualShield2: "Usually the reference is saved in open LOS, then compared against the shielded condition.",
    manualShield3: "Read shield loss, path loss, and delta versus reference together.",
    manualNotesTitle: "5. Notes",
    manualNotes1: "This simulator is for training, so it does not reproduce every menu and calibration action of a real instrument.",
    manualNotes2: "A useful next extension is to add PCI test flow and saved presets for shielding setups.",
  },
  koreanStaticText: {
    navShield: "차폐 실험",
    navPci: "PCI 실험",
    navToolsLabel: "보조 측정 장비",
    scopeEyebrow: "보조 측정 장비",
    generatorEyebrow: "보조 측정 장비",
    shieldAntennaEyebrow: "차폐 실험 STEP 1 / 4",
    shieldAntennaTitle: "안테나 설정",
    shieldAntennaDescription: "먼저 송신 안테나, 수신 안테나, 차폐함 슬롯을 배치하고 LOS 환경을 만듭니다.",
    shieldAntennaNextButton: "다음: 실험 수치 입력",
    shieldSetupEyebrow: "차폐 실험 STEP 2 / 4",
    shieldSetupTitle: "실험 수치 입력",
    shieldSetupDescription: "LOS 거리, 차폐 조건, analyzer sweep 값을 입력하고 제네레이터 설정 단계로 이동합니다.",
    shieldSetupBackButton: "이전: 안테나 설정",
    shieldSetupNextButton: "다음: 제네레이터",
    flowSummaryEyebrow: "실험 요약",
    flowSummaryTitle: "입력된 수치",
    flowSummaryTx: "송신 안테나",
    flowSummaryRx: "수신 안테나",
    flowSummaryPlacement: "수신 위치",
    flowSummaryDistance: "LOS 거리",
    flowSummaryShieldMaterial: "차폐 재질",
    flowSummaryShieldEffectiveness: "차폐 성능",
    flowSummaryShieldLeakage: "누설",
    flowSummaryGeneratorFreq: "제네레이터 주파수",
    flowSummaryGeneratorLevel: "제네레이터 레벨",
    flowSummaryGeneratorState: "송신 상태",
    flowSummaryCenter: "Center",
    flowSummarySpan: "Span",
    flowSummaryRbw: "RBW",
    supportToolsEyebrow: "보조 측정 장비",
    supportToolsTitle: "장비 바로가기",
    supportToolsNote: "실험 진행 중 필요할 때 보조 측정 장비 화면으로 이동해 현재 수치와 측정 화면을 함께 확인할 수 있습니다.",
    quickSetupEyebrow: "직접 입력",
    quickSetupTitle: "2. 실험 수치 바로 입력",
    quickSetupNote: "안테나 배치가 끝나면 여기에서 LOS 거리, 차폐 값, analyzer sweep 값을 바로 입력하고 다음 단계로 제네레이터를 설정합니다.",
    quickDistanceLabel: "LOS 거리",
    quickShieldEffectivenessLabel: "차폐 성능",
    quickShieldLeakageLabel: "누설",
    quickCenterLabel: "Analyzer Center",
    quickSpanLabel: "Span",
    quickRbwLabel: "RBW",
    quickSetupToGeneratorButton: "3. 제네레이터 설정하러 가기",
    generatorFreqNote: "여기서 입력한 값은 대기 상태로 저장됩니다. 실제 애널라이저 반영은 발사 버튼을 눌렀을 때만 이뤄집니다.",
    generatorLevelNote: "LEVEL 버튼으로 레벨을 맞춘 뒤 발사 버튼을 누르면 설정한 dBm 값으로 송신됩니다.",
    generatorFireButton: "발사!",
    generatorStopButton: "정지",
    generatorHint3: "값을 정한 뒤 발사 버튼을 눌러야 analyzer에 피크가 나타나고, 정지를 누르면 다시 노이즈 플로어 위주로 보입니다.",
    generatorToAntennaButton: "이전: 실험 수치 입력",
  },
  uiText: {
    ko: {
      pageTitle: "전자파 시험 시뮬레이터",
      languageButton: "English",
      runStateRunning: "동작",
      runStateStopped: "정지",
      runToggleRun: "실행",
      runToggleStop: "정지",
      overlayTime: "시간",
      overlayTrigger: "트리거",
      analyzerLinkLos: "LOS ACTIVE",
      analyzerLinkShield: "SHIELD ACTIVE",
      analyzerLinkOutOfBand: "OUT OF BAND",
      stageEmptyName: "미배치",
      stageEmptyBand: "안테나를 끌어오세요",
      stageOpenBand: "개방 수신 슬롯으로 사용할 수 있습니다",
      stageShieldBand: "수신 안테나를 차폐함으로 이동하세요",
      stageShieldOn: "차폐함 ON",
      stageShieldOff: "차폐함 OFF",
      generatorOutputOn: "발사 중",
      generatorOutputOff: "발사 대기",
      generatorOutputEnable: "RF ON",
      generatorOutputDisable: "RF OFF",
      generatorPendingFeed: "발사 대기",
      baselineStored: "저장됨",
      baselineEmpty: "없음",
      summaryOpen: "개방 LOS",
      summaryShielded: "차폐 상자 적용",
      summaryCarrierInBand: "공통 대역 내",
      summaryCarrierOutBand: "공통 대역 밖",
      summaryCarrierNoOverlap: "공통 대역 없음",
      statusNoteGeneratorOff: "제네레이터가 아직 발사되지 않았거나 정지 상태입니다. 발사 버튼을 눌러야 analyzer에서 신호 피크를 볼 수 있습니다.",
      statusNoteOpen: "현재는 개방 LOS 상태입니다. 이 상태에서 저장한 기준값을 차폐 상자 상태와 비교하면 감쇠량을 읽기 쉽습니다.",
      statusNoteShield: "수신 안테나가 가상 차폐 상자 안에 있습니다. 차폐 재질과 누설량 설정에 따라 기준값 대비 감쇠가 바뀝니다.",
      statusNoteOutOfBand: "현재 송신 주파수가 송신/수신 안테나 공통 대역을 벗어나 있습니다. 실제 측정처럼 수신 레벨이 크게 떨어집니다.",
      statusNoteNoOverlap: "선택한 송신 안테나와 수신 안테나 사이에 공통 주파수 대역이 없습니다.",
    },
    en: {
      pageTitle: "EMC Test Simulator",
      languageButton: "한국어",
      runStateRunning: "RUN",
      runStateStopped: "STOP",
      runToggleRun: "Run",
      runToggleStop: "Stop",
      overlayTime: "Time",
      overlayTrigger: "Trigger",
      analyzerLinkLos: "LOS ACTIVE",
      analyzerLinkShield: "SHIELD ACTIVE",
      analyzerLinkOutOfBand: "OUT OF BAND",
      stageEmptyName: "Unassigned",
      stageEmptyBand: "Drag an antenna card here",
      stageOpenBand: "Use this as the open receive slot",
      stageShieldBand: "Move the receive antenna into the shield box",
      stageShieldOn: "Shield Box ON",
      stageShieldOff: "Shield Box OFF",
      generatorOutputOn: "LIVE",
      generatorOutputOff: "STANDBY",
      generatorOutputEnable: "RF ON",
      generatorOutputDisable: "RF OFF",
      generatorPendingFeed: "Standby",
      baselineStored: "Stored",
      baselineEmpty: "Empty",
      summaryOpen: "Open LOS",
      summaryShielded: "Shield Box Enabled",
      summaryCarrierInBand: "Inside overlap band",
      summaryCarrierOutBand: "Outside overlap band",
      summaryCarrierNoOverlap: "No overlap band",
      statusNoteGeneratorOff: "The generator is standing by. Press Fire to send the signal and reveal the analyzer peak.",
      statusNoteOpen: "The setup is currently in open LOS. Store the reference here first, then compare it against the shielded condition.",
      statusNoteShield: "The receive antenna is inside the virtual shield box. Material and leakage settings will change the attenuation against the reference.",
      statusNoteOutOfBand: "The current transmit frequency is outside the overlap band of the selected antennas, so the received level drops sharply.",
      statusNoteNoOverlap: "The selected transmit and receive antennas do not share any common frequency band.",
    },
  },
};

Object.assign(window.SIM_DATA.englishStaticText, {
  navAnalyzer: "Spectrum Analyzer",
  shieldSetupDescription: "Set LOS distance, shielding conditions, and spectrum analyzer sweep values before moving to the generator step.",
  workflowAnalyzerTitle: "Reference / Spectrum Analyzer Check",
  workflowCenterLabel: "Center",
  quickSetupNote: "After placing the antennas, enter the LOS distance, shielding values, and spectrum analyzer sweep values here, then move to the generator step.",
  quickCenterLabel: "Center",
  analyzerSweepTitle: "Spectrum Analyzer",
  generatorSummaryAnalyzer: "Spectrum Analyzer Feed",
  generatorHint3: "The spectrum analyzer peak appears only after Fire. Press Stop to return near the noise floor.",
  manualStart1: "From the home screen, enter the shielding test first, then use the oscilloscope and spectrum analyzer from the top navigation as supporting tools when needed.",
  manualStart3: "On the spectrum analyzer, define the LOS antennas and transmit settings, then store a reference.",
  manualAnalyzerTitle: "3. Spectrum Analyzer",
  analyzerScreenModeLabel: "Spectrum",
  analyzerScreenStatusLabel: "Ref Level",
  analyzerSoftkeyCenter: "Center",
  analyzerSoftkeyStep: "CF StepSize",
  analyzerSoftkeyRef: "Ref Level",
  analyzerSoftkeyStart: "Start",
  analyzerSoftkeyStop: "Stop",
  analyzerSoftkeyTrack: "Signal Track",
  analyzerHardkeyFreq: "FREQ / CHANNEL",
  analyzerHardkeySpan: "SPAN",
  analyzerHardkeyAmpt: "AMPT / SCALE",
  analyzerHardkeyAuto: "AUTO SET",
  analyzerHardkeyBw: "BW",
  analyzerHardkeySweep: "SWEEP",
  analyzerHardkeyTrace: "TRACE",
  analyzerHardkeyTrig: "TRIG",
  analyzerHardkeyMeas: "MEAS",
  analyzerHardkeyMeasConfig: "MEAS CONFIG",
  analyzerHardkeyLines: "LINES",
  analyzerHardkeyIo: "INPUT / OUTPUT",
  analyzerHardkeyMarker: "MKR",
  analyzerHardkeyPeak: "PEAK SEARCH",
  analyzerHardkeyView: "VIEW SIGNAL",
  analyzerHardkeyClear: "CLEAR REF",
  analyzerEntryTargetLabel: "Selected",
  analyzerEntryHint: "Enter numbers, then press a unit key or ENTER.",
  analyzerKeyEsc: "ESC",
  analyzerKeyBackspace: "BACK SPACE",
  analyzerKeyEnter: "ENTER",
  analyzerTargetCenter: "Center",
  analyzerTargetSpan: "Span",
  analyzerTargetRbw: "RBW",
  analyzerTargetRef: "Ref Level",
  analyzerStepLabel: "Step",
});

Object.assign(window.SIM_DATA.koreanStaticText, {
  navAnalyzer: "\uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30",
  shieldSetupDescription: "LOS \uac70\ub9ac, \ucc28\ud3d0 \uc870\uac74, \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30 sweep \uac12\uc744 \uc785\ub825\ud558\uace0 \uc81c\ub124\ub808\uc774\ud130 \uc124\uc815 \ub2e8\uacc4\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.",
  workflowAnalyzerTitle: "\uae30\uc900\uac12 / \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30 \ud655\uc778",
  workflowCenterLabel: "Center",
  quickSetupNote: "\uc548\ud14c\ub098 \ubc30\uce58\uac00 \ub05d\ub098\uba74 \uc5ec\uae30\uc5d0\uc11c LOS \uac70\ub9ac, \ucc28\ud3d0 \uac12, \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30 sweep \uac12\uc744 \ubc14\ub85c \uc785\ub825\ud558\uace0 \ub2e4\uc74c \ub2e8\uacc4\ub85c \uc81c\ub124\ub808\uc774\ud130\ub97c \uc124\uc815\ud569\ub2c8\ub2e4.",
  quickCenterLabel: "Center",
  analyzerSweepTitle: "\uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30",
  generatorSummaryAnalyzer: "\uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30 \uc785\ub825",
  generatorHint3: "\uac12\uc744 \uc815\ud55c \ub4a4 \ubc1c\uc0ac \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc57c \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30\uc5d0 \ud53c\ud06c\uac00 \ub098\ud0c0\ub098\uace0, \uc815\uc9c0\ub97c \ub204\ub974\uba74 \ub2e4\uc2dc \ub178\uc774\uc988 \ud50c\ub85c\uc5b4 \uc704\uc8fc\ub85c \ubcf4\uc785\ub2c8\ub2e4.",
  manualStart1: "\ud648 \ud654\uba74\uc5d0\uc11c \ucc28\ud3d0 \uc2e4\ud5d8\uc73c\ub85c \uc9c4\uc785\ud558\uace0, \ud544\uc694\ud558\uba74 \uc0c1\ub2e8 \uba54\ub274\uc5d0\uc11c \uc624\uc2e4\ub85c\uc2a4\ucf54\ud504\uc640 \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30\ub97c \ubcf4\uc870 \ub3c4\uad6c\ub85c \uc0ac\uc6a9\ud569\ub2c8\ub2e4.",
  manualStart3: "\uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30\uc5d0\uc11c\ub294 LOS \uc548\ud14c\ub098\uc640 \uc1a1\uc2e0 \uc870\uac74\uc744 \uc815\ud55c \ub4a4 \uae30\uc900\uac12\uc744 \uc800\uc7a5\ud569\ub2c8\ub2e4.",
  manualAnalyzerTitle: "3. \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30",
});

Object.assign(window.SIM_DATA.uiText.ko, {
  referenceVisible: "\ud45c\uc2dc \uc911",
  referenceHidden: "\uc228\uae40",
  statusNoteGeneratorOff: "\uc81c\ub124\ub808\uc774\ud130\uac00 \uc544\uc9c1 \ubc1c\uc0ac\ub418\uc9c0 \uc54a\uc558\uac70\ub098 \uc815\uc9c0 \uc0c1\ud0dc\uc785\ub2c8\ub2e4. \ubc1c\uc0ac \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc57c \uc2a4\ud399\ud2b8\ub7fc \ubd84\uc11d\uae30\uc5d0\uc11c \uc2e0\ud638 \ud53c\ud06c\ub97c \ubcfc \uc218 \uc788\uc2b5\ub2c8\ub2e4.",
});

Object.assign(window.SIM_DATA.uiText.en, {
  referenceVisible: "Visible",
  referenceHidden: "Hidden",
  statusNoteGeneratorOff: "The generator is standing by. Press Fire to send the signal and reveal the spectrum analyzer peak.",
});
